/*
 * File: index.jsx
 * Project: codelabs-boilderplate
 * Created Date: Sun Sep 25 2022 2:12:14 AM
 * Author: Mohammed Parveez <ahamed.parveez@gmail.com>
 * ------------------------------------
 *
 * Copyright (c) 2022 All rights reserved by Codelabs
 * ------------------------------------
 */

import Head from 'next/head';
import Image from 'next/image';
import LoginLayout from 'src/layouts/LoginLayout';
import okBoyScooter from '@Assets/images/okboy-scooter.png';
import okBoyLogo from '@Assets/images/okboys_logo.png';
import Button from '@Atoms/Button';
import { Input } from 'antd';

const Login = () => {
  return (
    <>
      <Head>
        <title>Franchise - OK Boys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginLayout>
        <div className="p-4 flex gap-20 w-full justify-center">
          <div className="flex flex-1 flex-col justify-center px-20">
            <div className="img items-start flex justify-self-center">
              <Image src={okBoyLogo.src} height={50} width={100} objectFit="contain" />
            </div>
            <h1 className="text-defaultText font-bold mb-10">FRANCHISE</h1>
            <div className="flex flex-col space-y-4">
              <div className="flex flex-col mb-4 space-y-2">
                <p className="okp">Mobile Number</p>
                <Input placeholder="Basic usage" className="okInput" />
              </div>
              <div className="flex flex-col mb-4 space-y-2">
                <p className="okp">OTP</p>
                <Input placeholder="Basic usage" className="okInput" />
              </div>
              <div className="flex justify-end">
                <div className="flex w-[50%]">
                  <Button name="Submit" handleClick={() => {}} disabled />
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-1 justify-center px-20">
            <div className="img">
              <Image src={okBoyScooter.src} width={300} height={300} objectFit="contain" />
            </div>
          </div>
        </div>
      </LoginLayout>
    </>
  );
};

export default Login;
